[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.build]
cmds = ['npm install --prefix backend', 'npm run build --prefix backend --if-present']

[phases.start]
cmd = 'npm start --prefix backend'

[variables]
NODE_ENV = 'production'